version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    environment:
      # создаём суперпользователя и базу
      POSTGRES_USER: smarthome_user
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: smarthome_db
      volumes:
        - pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      restart: unless-stopped

  temperature-api:
    build:
      context: ./apps/temperature-api
      dockerfile: Dockerfile
      image: temperature-api:latest
      environment:
        SERVER_PORT: 8081
        # параметры подключения к БД
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smarthome_db
        SPRING_DATASOURCE_USERNAME: smarthome_user
        SPRING_DATASOURCE_PASSWORD: supersecretpassword
      depends_on:
        - postgres
      ports:
        - "8081:8081"
      restart: unless-stopped

    volumes:
      pgdata:

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network

volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge
